default_language_version:
  python: python3.13

default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        files: ^TP-FINAL/src/
      - id: end-of-file-fixer
        files: ^TP-FINAL/src/
      - id: check-added-large-files
        files: ^TP-FINAL/src/
      - id: check-ast
        files: ^TP-FINAL/src/.*\.py$

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: ^TP-FINAL/src/.*\.py$

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        files: ^TP-FINAL/src/.*\.py$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.7
    hooks:
      - id: ruff
        files: ^TP-FINAL/src/.*\.py$
        args: ["--fix", "--exit-non-zero-on-fix"]
